export const USERNAME_CANNOT_BE_NULL = 'Username cannot be empty!'
export const EMAIL_CANNOT_BE_NULL = 'Email cannot be empty!'
export const PASSWORD_CANNOT_BE_NULL = 'Password cannot be empty!'
export const PASSWORD_MUST_CONTAIN_EIGHT_CHARACTERS_OR_MORE = 'Passwords must have 8 Characters or more !'
export const PASSWORDS_DO_NOT_MATCH = 'Passwords do not match !'