import Head from "next/head";
import Header from "../components/Header";
import Lottie from "react-lottie";
import animationData from "../assets/53558-mexican-fella.json";
import WelcomeTitle from "../components/WelcomeTitle";

import { useRouter } from "next/router";

import styles from "../styles/Home.module.scss";

export default function Home() {
  const router = useRouter();
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <Header></Header>
          <WelcomeTitle></WelcomeTitle>
          <Lottie options={defaultOptions} height={400} width={400}></Lottie>
          <div
            style={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "center",
            }}
          >
            <button
              onClick={() => {
                router.push("/register");
              }}
            >
              Registrar
            </button>
            <button
              onClick={() => {
                router.push("/login");
              }}
            >
              Login
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
