import Head from "next/head";
import Header from "../components/Header";
import WelcomeTitle from "../components/WelcomeTitle";

import styles from "../styles/Home.module.scss";
import HomeDoubleButton from "../components/Buttons/HomeDoubleButton";
import MexicanLottie from "../components/MexicanLottie";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <Header />
          <WelcomeTitle />
          <MexicanLottie />
          <HomeDoubleButton />
        </div>
      </main>
    </div>
  );
}
