import Head from "next/head";
import Header from "../components/Header";
import Lottie from "react-lottie";
import animationData from "../assets/53558-mexican-fella.json";
import Title from "../components/Title";
import WelcomeTitle from "../components/WelcomeTitle";

export default function Home() {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: animationData,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header></Header>
        <WelcomeTitle></WelcomeTitle>
        <Lottie options={defaultOptions} height={400} width={400}></Lottie>
      </main>
    </div>
  );
}
